---
- hosts: app
  sudo: true
  vars:
    hostname: server-production
    environtment: production
    ruby_version: 2.1.2
    rbenv_root: /home/vagrant/.rbenv
    rbenv_bin: /home/vagrant/.rbenv/libexec/rbenv
  roles:
    - common
    - rvm
    - nginx
    - mysql
    - rails
    #- troubleshooting