---
- hosts: app
  sudo: true
  vars:
    nginx_user: nginx
    hostname: vagrant-ansible-rails
    environtment: vagrant
    ruby_version: 2.1.2
    rbenv_root: /home/vagrant/.rbenv
    rbenv_bin: /home/vagrant/.rbenv/libexec/rbenv
  roles:
    - common
    - iptables
    - rvm
    - nginx
    - mysql
    - rails
